CREATE TABLE ip(ip INT(4) UNSIGNED, contrib INT UNSIGNED DEFAULT 0);
CREATE TABLE stat(uvisit INT UNSIGNED DEFAULT 0, contrib INT UNSIGNED DEFAULT 0, q1yes INT UNSIGNED DEFAULT 0, q1no INT UNSIGNED DEFAULT 0, q2yes INT UNSIGNED DEFAULT 0, q2no INT UNSIGNED DEFAULT 0);
INSERT INTO stat SET uvisit=0;
